name: Development Release

on:
  push:
    branches: [development]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate development version
        id: version
        run: |
          BASE_VERSION=$(cat VERSION | tr -d '\n')
          DATE=$(date +'%Y%m%d')
          SHORT_SHA=${GITHUB_SHA::7}
          DEV_VERSION="${BASE_VERSION}-dev.${DATE}.${SHORT_SHA}"

          echo "version=${DEV_VERSION}" >> $GITHUB_OUTPUT
          echo "base_version=${BASE_VERSION}" >> $GITHUB_OUTPUT
          echo "Generated version: ${DEV_VERSION}"

      - name: Build for Linux and Windows
        run: |
          mkdir -p artifacts

          # Run build using docker compose
          docker compose run --rm build

          # Copy generated artifacts
          if [ -f "dist/sbagen+-linux64" ]; then
            cp dist/sbagen+-linux64 artifacts/sbagen+-linux64
          fi

          if [ -f "dist/sbagen+-linux32" ]; then
            cp dist/sbagen+-linux32 artifacts/sbagen+-linux32
          fi

          if [ -f "dist/sbagen+-windows-setup.exe" ]; then
            cp dist/sbagen+-windows-setup.exe artifacts/sbagen+-windows-setup.exe
          fi

      - name: Generate SHA256 checksums
        run: |
          cd artifacts
          find . -type f -exec sha256sum {} \; | sort > ../checksums.txt
          cat ../checksums.txt

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sbagen-plus-${{ steps.version.outputs.version }}
          path: |
            artifacts/
            checksums.txt
          retention-days: 30

  create-release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: sbagen-plus-${{ needs.build.outputs.version }}

      - name: Generate release body with checksums
        run: |
          echo "**This is a development version and may contain bugs or unstable features.**" > release_body.md
          echo "" >> release_body.md
          echo "SHA256SUM:" >> release_body.md

          if [ -f checksums.txt ]; then
            while IFS= read -r line; do
              # Extract hash and filename
              hash=$(echo "$line" | cut -d' ' -f1)
              file=$(echo "$line" | cut -d' ' -f3- | sed 's|^\./||')
              echo "$hash $file" >> release_body.md
            done < checksums.txt
          fi

          cat release_body.md

      - name: Create Development Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ needs.build.outputs.version }}
          name: "Development Release v${{ needs.build.outputs.version }}"
          body_path: release_body.md
          files: |
            artifacts/*
          prerelease: true
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
